-- Full database expansion for Prem Gas Solution
-- Includes all business tables with foreign keys, indexes, and constraints
-- Updated 2026-07-16

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `gas_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `chemical_formula` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `default_price_per_kg` decimal(10,2) DEFAULT 0.00,
  `refill_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sizes` varchar(255) DEFAULT '10L,40L,47L',
  `size_prices` text DEFAULT NULL,
  `size_refill_costs` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `hsn_code` varchar(8) DEFAULT '280440',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `customers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `mobile` varchar(20) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `gst_number` varchar(15) DEFAULT NULL,
  `customer_type` enum('refill','rental') NOT NULL DEFAULT 'refill',
  `deposit_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `advance_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `active_cylinders_count` int(11) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') DEFAULT 'active',
  `login_enabled` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `state_code` int(11) DEFAULT NULL,
  `state_name` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `pincode` varchar(10) DEFAULT NULL,
  `registration_type` enum('regular','composition','unregistered','others') DEFAULT 'regular',
  `credit_used` decimal(10,2) DEFAULT 0.00,
  `credit_status` enum('good','warning','blocked') NOT NULL DEFAULT 'good',
  `credit_terms` int(11) DEFAULT 30,
  `credit_limit` decimal(10,2) DEFAULT 0.00,
  `last_login` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(255) DEFAULT NULL,
  `remember_expires` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mobile` (`mobile`),
  KEY `customer_type` (`customer_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `mobile` varchar(20) NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `gst_number` varchar(15) DEFAULT NULL,
  `gst_registration_type` enum('regular','composition','unregistered') DEFAULT 'regular',
  `pan` varchar(10) DEFAULT NULL,
  `tan` varchar(10) DEFAULT NULL,
  `active_refill_count` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `state_code` int(11) DEFAULT NULL,
  `state_name` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `pincode` varchar(10) DEFAULT NULL,
  `bank_account_holder` varchar(150) DEFAULT NULL,
  `bank_account_number` varchar(50) DEFAULT NULL,
  `bank_ifsc` varchar(20) DEFAULT NULL,
  `bank_name` varchar(200) DEFAULT NULL,
  `bank_branch` varchar(200) DEFAULT NULL,
  `payment_terms` int(11) DEFAULT 30,
  `notes` text DEFAULT NULL,
  `registration_type` enum('regular','composition','unregistered','others') DEFAULT 'regular',
  `contact_person` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9998 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cylinders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `serial_number` varchar(100) NOT NULL,
  `barcode` varchar(100) DEFAULT NULL,
  `gas_type_id` int(11) DEFAULT NULL,
  `size_capacity` varchar(50) DEFAULT NULL,
  `status` enum('filled','empty','in_use','with_customer','sent_to_vendor','under_maintenance','borrowed_from_partner','lent_to_partner','with_partner','returned_to_partner','returned_to_consumer','received_for_refill','borrowed_from_vendor','returned_to_vendor') NOT NULL DEFAULT 'empty',
  `last_refill_date` date DEFAULT NULL,
  `last_inspection_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `ownership_type` enum('owned','partner_owned','consumer_owned','vendor_owned') NOT NULL DEFAULT 'owned',
  `exchange_status` enum('none','open','closed') NOT NULL DEFAULT 'none',
  `lifecycle_status` enum('active','archived','settled') NOT NULL DEFAULT 'active',
  `active_exchange_id` int(11) DEFAULT NULL,
  `borrow_date` date DEFAULT NULL,
  `daily_rent_rate` decimal(10,2) DEFAULT 0.00,
  `free_days` int(11) DEFAULT 0,
  `purchase_price` decimal(10,2) DEFAULT 0.00,
  `current_customer_id` int(11) DEFAULT NULL,
  `current_vendor_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `purchase_id` int(11) DEFAULT NULL,
  `current_partner_id` int(11) DEFAULT NULL,
  `original_owner_customer_id` int(11) DEFAULT NULL,
  `is_customer_refill_cylinder` tinyint(1) NOT NULL DEFAULT 0,
  `current_refill_cost` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_refill_vendor_id` int(11) DEFAULT NULL,
  `last_refill_batch_id` int(11) DEFAULT NULL,
  `last_refill_lot_id` int(11) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(100) DEFAULT NULL,
  `transaction_log` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `serial_number` (`serial_number`),
  KEY `idx_customer_id` (`current_customer_id`),
  KEY `idx_gas_type` (`gas_type_id`),
  KEY `idx_status` (`status`),
  KEY `idx_ownership` (`ownership_type`),
  KEY `fk_cylinders_original_owner` (`original_owner_customer_id`),
  CONSTRAINT `fk_cylinders_original_owner` FOREIGN KEY (`original_owner_customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `inventory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `total_stock` int(11) NOT NULL DEFAULT 0,
  `filled_stock` int(11) NOT NULL DEFAULT 0,
  `empty_stock` int(11) NOT NULL DEFAULT 0,
  `with_customer_stock` int(11) NOT NULL DEFAULT 0,
  `sent_to_vendor_stock` int(11) NOT NULL DEFAULT 0,
  `maintenance_stock` int(11) NOT NULL DEFAULT 0,
  `min_alert_threshold` int(11) NOT NULL DEFAULT 2,
  `borrowed_from_partner_stock` int(11) NOT NULL DEFAULT 0,
  `borrowed_from_vendor_stock` int(11) NOT NULL DEFAULT 0,
  `returned_to_vendor_stock` int(11) NOT NULL DEFAULT 0,
  `received_for_refill_stock` int(11) NOT NULL DEFAULT 0,
  `lent_to_partner_stock` int(11) NOT NULL DEFAULT 0,
  `with_partner_stock` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `gas_size` (`gas_type_id`,`size_capacity`),
  CONSTRAINT `inventory_ibfk_1` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `refill_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(100) DEFAULT NULL,
  `invoice_date` datetime DEFAULT NULL,
  `customer_id` int(11) NOT NULL,
  `order_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `subtotal` decimal(10,2) NOT NULL DEFAULT 0.00,
  `deposit_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `deposit_type` varchar(50) DEFAULT NULL,
  `deposit_settled` decimal(10,2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `discount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `round_off` decimal(10,2) NOT NULL DEFAULT 0.00,
  `grand_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `due_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `advance_used` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_status` enum('paid','pending','partial') NOT NULL DEFAULT 'pending',
  `payment_method` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `include_in_gst_return` tinyint(1) DEFAULT 1,
  `gst_status` enum('draft','filed','amended') DEFAULT 'draft',
  `invoice_type` enum('b2b','b2c','credit_note','debit_note') DEFAULT 'b2b',
  `place_of_supply_state_code` int(11) DEFAULT NULL,
  `reverse_charge` tinyint(1) DEFAULT 0,
  `business_name` varchar(50) DEFAULT 'nutan_gases',
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `vehicle_number` varchar(100) DEFAULT NULL,
  `is_credit_order` tinyint(1) NOT NULL DEFAULT 0,
  `order_type` varchar(50) NOT NULL DEFAULT 'refill_with_exchange',
  PRIMARY KEY (`id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `refill_orders_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `refill_order_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `refill_order_id` int(11) NOT NULL,
  `gas_type_id` int(11) DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `cylinder_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `qty` int(11) NOT NULL DEFAULT 1,
  `price_per_unit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `vendor_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `refill_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `is_rental` tinyint(1) NOT NULL DEFAULT 0,
  `deposit_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `hsn_code` varchar(8) DEFAULT NULL,
  `itc_eligible` tinyint(1) DEFAULT 1,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  `returned_cylinder_id` int(11) DEFAULT NULL,
  `rent_per_day` decimal(10,2) NOT NULL DEFAULT 0.00,
  `free_days` int(11) NOT NULL DEFAULT 0,
  `damage_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `damage_description` varchar(255) DEFAULT NULL,
  `sell_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sold_cylinder_serial` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `refill_order_id` (`refill_order_id`),
  KEY `gas_type_id` (`gas_type_id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `idx_refill_order_items_returned_cylinder` (`returned_cylinder_id`),
  CONSTRAINT `refill_order_items_ibfk_1` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `refill_order_items_ibfk_2` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`),
  CONSTRAINT `refill_order_items_ibfk_3` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(100) NOT NULL,
  `refill_order_id` int(11) NOT NULL,
  `invoice_date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  `customer_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`),
  KEY `refill_order_id` (`refill_order_id`),
  CONSTRAINT `invoices_ibfk_1` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lot_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `refill_order_id` int(11) DEFAULT NULL,
  `customer_refill_service_id` int(11) DEFAULT NULL,
  `vendor_batch_id` int(11) DEFAULT NULL,
  `amount` decimal(10,2) NOT NULL,
  `payment_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `payment_method` varchar(50) NOT NULL,
  `payment_type` enum('refill_payment','deposit_added','deposit_refunded','vendor_payment','refill_service_payment') NOT NULL,
  `payment_subtype` varchar(20) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `ledger_group_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customer_id` (`customer_id`),
  KEY `vendor_id` (`vendor_id`),
  KEY `refill_order_id` (`refill_order_id`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `payments_ibfk_2` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `payments_ibfk_3` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cylinder_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cylinder_id` int(11) NOT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `transaction_type` enum('refill','issue_to_customer','return_from_customer','send_to_vendor','receive_from_vendor','maintenance','partner_borrow','partner_return','partner_lend','partner_receive_back','vendor_borrow','vendor_return') NOT NULL,
  `transaction_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `notes` text DEFAULT NULL,
  `ledger_group_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `customer_id` (`customer_id`),
  KEY `vendor_id` (`vendor_id`),
  CONSTRAINT `cylinder_transactions_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `cylinder_transactions_ibfk_3` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `role` enum('super_admin','billing_clerk','warehouse_supervisor') NOT NULL DEFAULT 'billing_clerk',
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `activity_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `action` varchar(255) NOT NULL,
  `details` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `partners` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(200) NOT NULL,
  `contact_person` varchar(150) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `gst_number` varchar(20) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `state_code` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `company_name` (`company_name`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `partner_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `partner_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `transaction_type` enum('borrowed_from_partner','returned_to_partner','lent_to_partner','received_back_from_partner','borrowed_from_vendor','returned_to_vendor') NOT NULL,
  `transaction_date` date NOT NULL,
  `notes` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `partner_id` (`partner_id`),
  KEY `transaction_type` (`transaction_type`),
  KEY `transaction_date` (`transaction_date`),
  CONSTRAINT `partner_transactions_ibfk_1` FOREIGN KEY (`partner_id`) REFERENCES `partners` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `partner_transaction_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `transaction_id` int(11) NOT NULL,
  `cylinder_id` int(11) DEFAULT NULL,
  `serial_number` varchar(100) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `status_before` varchar(50) DEFAULT NULL,
  `status_after` varchar(50) NOT NULL,
  `daily_rent_rate` decimal(10,2) DEFAULT 0.00,
  `free_days` int(11) DEFAULT 0,
  `days_held` int(11) DEFAULT 0,
  `rent_accrued` decimal(10,2) DEFAULT 0.00,
  `rent_paid` decimal(10,2) DEFAULT 0.00,
  `damage_amount` decimal(10,2) DEFAULT 0.00,
  `payment_status` enum('pending','cleared') DEFAULT 'cleared',
  PRIMARY KEY (`id`),
  KEY `transaction_id` (`transaction_id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `gas_type_id` (`gas_type_id`),
  CONSTRAINT `partner_transaction_items_ibfk_1` FOREIGN KEY (`transaction_id`) REFERENCES `partner_transactions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `partner_transaction_items_ibfk_2` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `partner_transaction_items_ibfk_3` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `deposit_receipts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `receipt_number` varchar(100) NOT NULL,
  `payment_id` int(11) NOT NULL,
  `customer_id` int(11) NOT NULL,
  `receipt_date` datetime NOT NULL,
  `damage_deduction` decimal(10,2) NOT NULL DEFAULT 0.00,
  `transaction_label` varchar(50) DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT NULL,
  `credit_settled` decimal(10,2) DEFAULT 0.00,
  `deposit_amount` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `ledger_group_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `receipt_number` (`receipt_number`),
  KEY `payment_id` (`payment_id`),
  KEY `receipt_number_2` (`receipt_number`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `deposit_receipts_ibfk_1` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `deposit_receipts_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_refill_batches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lot_id` int(11) DEFAULT NULL,
  `vendor_id` int(11) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `total_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `deduction_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `deduction_notes` varchar(255) DEFAULT NULL,
  `addition_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `addition_notes` varchar(255) DEFAULT NULL,
  `net_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cost_per_unit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `invoice_number` varchar(100) DEFAULT NULL,
  `received_date` datetime NOT NULL,
  `payment_status` enum('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid',
  `settlement_type` enum('paid','credit') NOT NULL DEFAULT 'credit',
  `paid_method` varchar(50) DEFAULT NULL,
  `paid_date` datetime DEFAULT NULL,
  `paid_reference` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `gas_type_id` (`gas_type_id`),
  KEY `vendor_id` (`vendor_id`),
  KEY `payment_status` (`payment_status`),
  KEY `received_date` (`received_date`),
  CONSTRAINT `vendor_refill_batches_ibfk_1` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`),
  CONSTRAINT `vendor_refill_batches_ibfk_2` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `product_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `purchase_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `stock_quantity` int(11) NOT NULL DEFAULT 0,
  `unit` varchar(50) DEFAULT 'piece',
  `min_alert_threshold` int(11) NOT NULL DEFAULT 5,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `hsn_code` varchar(8) DEFAULT NULL,
  `gst_rate` decimal(5,2) DEFAULT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `reorder_point` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cylinder_suppliers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(200) NOT NULL,
  `contact_person` varchar(150) DEFAULT NULL,
  `mobile` varchar(20) NOT NULL,
  `email` varchar(150) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `gst_number` varchar(20) DEFAULT NULL,
  `supplier_type` enum('cylinder','product','both') NOT NULL DEFAULT 'cylinder',
  `notes` text DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `state_code` int(11) DEFAULT NULL,
  `registration_type` enum('regular','composition','unregistered','others') DEFAULT 'regular',
  PRIMARY KEY (`id`),
  KEY `company_name` (`company_name`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cylinder_purchases` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(11) NOT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `invoice_date` date NOT NULL,
  `business_key` varchar(50) DEFAULT 'nutan_gases',
  `subtotal` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `cgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `igst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `grand_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cylinder_count` int(11) NOT NULL DEFAULT 0,
  `payment_status` enum('pending','paid','partial') NOT NULL DEFAULT 'pending',
  `notes` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `supplier_id` (`supplier_id`),
  KEY `invoice_date` (`invoice_date`),
  KEY `payment_status` (`payment_status`),
  CONSTRAINT `cylinder_purchases_ibfk_1` FOREIGN KEY (`supplier_id`) REFERENCES `cylinder_suppliers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cylinder_purchase_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_id` int(11) NOT NULL,
  `cylinder_id` int(11) DEFAULT NULL,
  `serial_number` varchar(100) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `unit_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `gas_type_id` (`gas_type_id`),
  KEY `purchase_id` (`purchase_id`),
  KEY `serial_number` (`serial_number`),
  CONSTRAINT `cylinder_purchase_items_ibfk_1` FOREIGN KEY (`purchase_id`) REFERENCES `cylinder_purchases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `cylinder_purchase_items_ibfk_2` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `cylinder_purchase_items_ibfk_3` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_refill_batch_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `batch_id` int(11) NOT NULL,
  `cylinder_id` int(11) DEFAULT NULL,
  `serial_number` varchar(100) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `cost_per_unit` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_batch_id` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(50) NOT NULL,
  `vendor_id` int(11) NOT NULL,
  `vendor_invoice_number` varchar(100) DEFAULT NULL,
  `lot_id` int(11) DEFAULT NULL,
  `invoice_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `business_key` varchar(50) DEFAULT NULL,
  `subtotal` decimal(10,2) NOT NULL DEFAULT 0.00,
  `deduction_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `addition_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `net_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `igst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `grand_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_status` enum('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid',
  `notes` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`),
  KEY `idx_vi_vendor` (`vendor_id`),
  KEY `idx_vi_status` (`payment_status`),
  KEY `idx_vi_date` (`invoice_date`),
  KEY `idx_vi_business` (`business_key`),
  KEY `idx_vi_lot` (`lot_id`),
  CONSTRAINT `vendor_invoices_ibfk_1` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`),
  CONSTRAINT `vendor_invoices_ibfk_2` FOREIGN KEY (`lot_id`) REFERENCES `dispatch_lots` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_invoice_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` int(11) NOT NULL,
  `batch_id` int(11) DEFAULT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `rate_per_unit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `gas_type_id` (`gas_type_id`),
  KEY `idx_vii_invoice` (`invoice_id`),
  KEY `idx_vii_batch` (`batch_id`),
  CONSTRAINT `vendor_invoice_items_ibfk_1` FOREIGN KEY (`invoice_id`) REFERENCES `vendor_invoices` (`id`) ON DELETE CASCADE,
  CONSTRAINT `vendor_invoice_items_ibfk_2` FOREIGN KEY (`batch_id`) REFERENCES `vendor_refill_batches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `vendor_invoice_items_ibfk_3` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_partner_ledger` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` enum('vendor','partner') NOT NULL,
  `entity_id` int(11) NOT NULL,
  `transaction_date` datetime NOT NULL,
  `transaction_type` varchar(50) NOT NULL COMMENT 'payment, advance, advance_utilized, due_created, rent_charge, current_payment, adjustment',
  `debit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `credit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `running_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `advance_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `due_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `settlement_status` enum('settled','partial','pending','') DEFAULT '',
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `entity_type` (`entity_type`,`entity_id`),
  KEY `transaction_date` (`transaction_date`),
  KEY `transaction_type` (`transaction_type`),
  KEY `idx_vpl_entity` (`entity_type`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vendor_activity_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vendor_id` int(11) NOT NULL,
  `activity_type` varchar(50) NOT NULL,
  `activity_date` datetime NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `details_json` text DEFAULT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `cylinder_count` int(11) DEFAULT 0,
  `amount` decimal(10,2) DEFAULT 0.00,
  `payment_method` varchar(50) DEFAULT NULL,
  `balance_after` decimal(10,2) DEFAULT NULL,
  `lot_number` varchar(50) DEFAULT NULL,
  `invoice_number` varchar(50) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_val_vendor_date` (`vendor_id`,`activity_date`),
  KEY `idx_val_reference` (`reference_type`,`reference_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `dispatch_lots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lot_number` varchar(50) NOT NULL,
  `vendor_id` int(11) NOT NULL,
  `driver_name` varchar(100) DEFAULT NULL,
  `vehicle_number` varchar(50) DEFAULT NULL,
  `dispatch_date` datetime NOT NULL,
  `expected_return_date` date DEFAULT NULL,
  `receive_date` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `estimated_total` decimal(10,2) DEFAULT 0.00,
  `cylinder_count` int(11) NOT NULL DEFAULT 0,
  `returned_count` int(11) NOT NULL DEFAULT 0,
  `lot_status` enum('open','partial_return','completed') NOT NULL DEFAULT 'open',
  `advance_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `gst_type` varchar(10) DEFAULT 'CGST/SGST',
  `gst_locked` tinyint(1) DEFAULT 0,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `final_refill_amount` decimal(10,2) DEFAULT 0.00,
  `final_gst_amount` decimal(10,2) DEFAULT 0.00,
  `final_total` decimal(10,2) DEFAULT 0.00,
  `gst_applicable` tinyint(1) DEFAULT 0,
  `total_paid` decimal(10,2) DEFAULT 0.00,
  `dispatch_transport_total` decimal(10,2) DEFAULT 0.00,
  `receive_transport_total` decimal(10,2) DEFAULT 0.00,
  `additional_payments` decimal(10,2) DEFAULT 0.00,
  `remaining_balance` decimal(10,2) DEFAULT 0.00,
  `payment_status` enum('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid',
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deduction_amount` decimal(10,2) DEFAULT 0.00,
  `deduction_notes` text DEFAULT NULL,
  `addition_amount` decimal(10,2) DEFAULT 0.00,
  `addition_notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `lot_number` (`lot_number`),
  KEY `vendor_id` (`vendor_id`),
  KEY `lot_status` (`lot_status`),
  KEY `payment_status` (`payment_status`),
  KEY `dispatch_date` (`dispatch_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `dispatch_lot_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lot_id` int(11) NOT NULL,
  `cylinder_id` int(11) NOT NULL,
  `serial_number` varchar(100) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `dispatch_status` enum('dispatched','received') NOT NULL DEFAULT 'dispatched',
  `receive_date` datetime DEFAULT NULL,
  `refill_cost` decimal(10,2) DEFAULT 0.00,
  `dispatch_transport_cost` decimal(10,2) DEFAULT 0.00,
  `receive_transport_cost` decimal(10,2) DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `taxable_amount` decimal(10,2) DEFAULT 0.00,
  `gst_amount` decimal(10,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `lot_id` (`lot_id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `dispatch_status` (`dispatch_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `supplier_ledger` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(11) NOT NULL,
  `transaction_date` datetime NOT NULL,
  `transaction_type` enum('purchase','payment','advance','adjustment') NOT NULL,
  `debit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `credit` decimal(10,2) NOT NULL DEFAULT 0.00,
  `running_balance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `supplier_id` (`supplier_id`),
  KEY `transaction_date` (`transaction_date`),
  KEY `transaction_type` (`transaction_type`),
  CONSTRAINT `supplier_ledger_ibfk_1` FOREIGN KEY (`supplier_id`) REFERENCES `cylinder_suppliers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `rental_returns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `cylinder_id` int(11) NOT NULL,
  `refill_order_item_id` int(11) DEFAULT NULL,
  `borrow_date` date NOT NULL,
  `return_date` date NOT NULL,
  `chargeable_days` int(11) NOT NULL DEFAULT 0,
  `daily_rate` decimal(10,2) NOT NULL,
  `rent_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `damage_charge` decimal(10,2) NOT NULL DEFAULT 0.00,
  `damage_description` varchar(255) DEFAULT NULL,
  `deposit_deducted` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_collected` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_method` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `ledger_group_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customer_id` (`customer_id`),
  KEY `cylinder_id` (`cylinder_id`),
  CONSTRAINT `rental_returns_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `rental_returns_ibfk_2` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `credit_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `refill_order_id` int(11) DEFAULT NULL,
  `transaction_type` enum('charge','payment','adjustment') NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `balance_after` decimal(10,2) NOT NULL,
  `description` text DEFAULT NULL,
  `transaction_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `due_date` date DEFAULT NULL,
  `ledger_group_id` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `refill_order_id` (`refill_order_id`),
  KEY `customer_id` (`customer_id`),
  KEY `transaction_date` (`transaction_date`),
  KEY `due_date` (`due_date`),
  CONSTRAINT `credit_transactions_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `credit_transactions_ibfk_2` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `customer_cylinder_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `refill_order_id` int(11) NOT NULL,
  `cylinder_id` int(11) NOT NULL,
  `status` enum('pending_receipt','received','at_vendor','sent_to_vendor','refilled','received_from_vendor','ready_for_pickup','delivered','archived') NOT NULL DEFAULT 'pending_receipt',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `refill_order_id` (`refill_order_id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `status` (`status`),
  CONSTRAINT `customer_cylinder_orders_ibfk_1` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `customer_cylinder_orders_ibfk_2` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `customer_refill_services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `cylinder_id` int(11) DEFAULT NULL,
  `serial_number` varchar(100) NOT NULL,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `refill_order_id` int(11) DEFAULT NULL,
  `service_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `service_charge` decimal(10,2) NOT NULL DEFAULT 0.00,
  `vendor_cost` decimal(10,2) NOT NULL DEFAULT 0.00,
  `refill_source` enum('vendor','warehouse') NOT NULL DEFAULT 'vendor',
  `payment_method` varchar(50) DEFAULT 'Cash',
  `payment_status` enum('paid','pending','partial') DEFAULT 'pending',
  `status` enum('received','sent_to_vendor','filled_from_vendor','returned_to_warehouse','returned_to_customer','cancelled') NOT NULL DEFAULT 'received',
  `sent_to_vendor_at` timestamp NULL DEFAULT NULL,
  `filled_from_vendor_at` timestamp NULL DEFAULT NULL,
  `returned_to_warehouse_at` timestamp NULL DEFAULT NULL,
  `returned_to_customer_at` timestamp NULL DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `gas_type_id` (`gas_type_id`),
  KEY `vendor_id` (`vendor_id`),
  KEY `customer_id` (`customer_id`),
  KEY `cylinder_id` (`cylinder_id`),
  KEY `status` (`status`),
  KEY `refill_order_id` (`refill_order_id`),
  CONSTRAINT `customer_refill_services_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `customer_refill_services_ibfk_2` FOREIGN KEY (`gas_type_id`) REFERENCES `gas_types` (`id`),
  CONSTRAINT `customer_refill_services_ibfk_3` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `customer_refill_services_ibfk_4` FOREIGN KEY (`cylinder_id`) REFERENCES `cylinders` (`id`) ON DELETE SET NULL,
  CONSTRAINT `customer_refill_services_ibfk_5` FOREIGN KEY (`refill_order_id`) REFERENCES `refill_orders` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gas_sizes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gas_type_id` int(11) NOT NULL,
  `size_capacity` varchar(50) NOT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_gas` (`gas_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `enquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT '',
  `phone` varchar(20) NOT NULL,
  `message` text DEFAULT NULL,
  `product` varchar(255) DEFAULT 'General Enquiry',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `newsletter_subscribers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ledger_groups` (
  `id` varchar(36) NOT NULL,
  `customer_id` int(11) NOT NULL,
  `group_type` varchar(50) NOT NULL COMMENT 'payment_received, payment_refunded, rental_return, credit_order, deposit_added',
  `title` varchar(255) DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT 0.00,
  `entry_date` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `customer_id` (`customer_id`),
  KEY `entry_date` (`entry_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `chart_of_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_code` varchar(20) NOT NULL,
  `account_name` varchar(200) NOT NULL,
  `account_type` enum('asset','liability','equity','income','expense') NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_code` (`account_code`),
  KEY `account_type` (`account_type`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `business_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `business_key` varchar(100) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `business_name` varchar(255) DEFAULT NULL,
  `tagline` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `gstin` varchar(50) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `logo_path` varchar(255) DEFAULT NULL,
  `logo_white_path` varchar(255) DEFAULT NULL,
  `bank_details` text DEFAULT NULL,
  `invoice_terms` text DEFAULT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` int(11) DEFAULT 587,
  `smtp_username` varchar(255) DEFAULT NULL,
  `smtp_password` varchar(255) DEFAULT NULL,
  `smtp_encryption` varchar(10) DEFAULT 'tls',
  `email_from_name` varchar(255) DEFAULT NULL,
  `email_from_address` varchar(255) DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `business_key` (`business_key`),
  UNIQUE KEY `uq_business_key` (`business_key`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module` varchar(50) DEFAULT 'gst',
  `gst_return_id` int(11) DEFAULT NULL,
  `reference_type` varchar(50) NOT NULL,
  `reference_id` int(11) NOT NULL,
  `field_name` varchar(100) DEFAULT NULL,
  `old_value` text DEFAULT NULL,
  `new_value` text DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `amended_by` varchar(100) DEFAULT NULL,
  `amended_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_module` (`module`),
  KEY `idx_return` (`gst_return_id`),
  KEY `idx_reference` (`reference_type`,`reference_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `bulk_operation_audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) DEFAULT NULL,
  `operation_type` varchar(50) NOT NULL,
  `action_key` varchar(50) NOT NULL DEFAULT '',
  `record_count` int(11) NOT NULL DEFAULT 0,
  `processed_count` int(11) NOT NULL DEFAULT 0,
  `skipped_count` int(11) NOT NULL DEFAULT 0,
  `before_state` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`before_state`)),
  `after_state` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`after_state`)),
  `impact_summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`impact_summary`)),
  `payment_changes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payment_changes`)),
  `gst_changes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gst_changes`)),
  `inventory_changes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`inventory_changes`)),
  `ledger_changes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ledger_changes`)),
  `execution_status` enum('success','failed') NOT NULL,
  `error_message` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `operation_type` (`operation_type`),
  KEY `execution_status` (`execution_status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `expenses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `expense_number` varchar(50) NOT NULL,
  `category_id` int(11) NOT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `vendor_name` varchar(150) DEFAULT NULL,
  `expense_date` date NOT NULL,
  `amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_type` enum('exclusive','inclusive') NOT NULL DEFAULT 'exclusive',
  `gst_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `taxable_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cgst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sgst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `igst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_total` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_method` varchar(50) NOT NULL DEFAULT 'cash',
  `payment_status` enum('paid','unpaid','partial') NOT NULL DEFAULT 'paid',
  `business_key` varchar(50) NOT NULL DEFAULT 'nutan_gases',
  `warehouse_branch` varchar(100) DEFAULT NULL,
  `vehicle_number` varchar(50) DEFAULT NULL,
  `driver_name` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_by_name` varchar(100) DEFAULT NULL,
  `status` enum('approved','rejected') NOT NULL DEFAULT 'approved',
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `expense_number` (`expense_number`),
  KEY `expense_date` (`expense_date`),
  KEY `category_id` (`category_id`),
  KEY `vendor_id` (`vendor_id`),
  KEY `payment_method` (`payment_method`),
  KEY `payment_status` (`payment_status`),
  KEY `business_key` (`business_key`),
  KEY `reference_type` (`reference_type`,`reference_id`),
  KEY `status` (`status`),
  KEY `is_deleted` (`is_deleted`),
  CONSTRAINT `expenses_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `expense_categories` (`id`),
  CONSTRAINT `expenses_ibfk_2` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `expense_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `gst_applicable` tinyint(1) NOT NULL DEFAULT 0,
  `default_gst_rate` decimal(5,2) DEFAULT NULL,
  `hsn_code` varchar(8) DEFAULT NULL,
  `auto_create` tinyint(1) NOT NULL DEFAULT 0,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `account_code` varchar(20) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `group_id` (`group_id`),
  KEY `is_active` (`is_active`),
  CONSTRAINT `expense_categories_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `expense_category_groups` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `expense_category_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `display_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `expense_attachments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `expense_id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `file_size` int(11) NOT NULL DEFAULT 0,
  `mime_type` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `expense_id` (`expense_id`),
  CONSTRAINT `expense_attachments_ibfk_1` FOREIGN KEY (`expense_id`) REFERENCES `expenses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_ledger` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` enum('vendor','customer','supplier','expense') NOT NULL,
  `entity_id` int(11) NOT NULL,
  `gst_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `taxable_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `gst_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `cgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sgst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `igst` decimal(10,2) NOT NULL DEFAULT 0.00,
  `input_output_type` enum('input','output') NOT NULL,
  `reference_type` varchar(50) NOT NULL,
  `reference_id` int(11) NOT NULL,
  `transaction_date` date NOT NULL,
  `gst_applicable` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_entity` (`entity_type`,`entity_id`),
  KEY `idx_type` (`input_output_type`),
  KEY `idx_ref` (`reference_type`,`reference_id`),
  KEY `idx_date` (`transaction_date`),
  KEY `idx_rate` (`gst_rate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_rates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rate_percent` decimal(5,2) NOT NULL,
  `label` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `rate_percent` (`rate_percent`)
) ENGINE=InnoDB AUTO_INCREMENT=1060 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_reconciliation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `business_key` varchar(100) NOT NULL,
  `financial_year` varchar(9) NOT NULL,
  `gst_period` varchar(7) NOT NULL,
  `vendor_gstin` varchar(15) NOT NULL,
  `vendor_invoice_number` varchar(100) NOT NULL,
  `vendor_invoice_date` date DEFAULT NULL,
  `purchase_gst_amount` decimal(10,2) DEFAULT 0.00,
  `purchase_taxable_value` decimal(10,2) DEFAULT 0.00,
  `itc_eligibility` enum('eligible','ineligible','reversal') DEFAULT 'eligible',
  `itc_amount` decimal(10,2) DEFAULT 0.00,
  `match_status` enum('matched','partial','missing','duplicate','blocked') DEFAULT 'missing',
  `gst_difference` decimal(10,2) DEFAULT 0.00,
  `portal_gst_amount` decimal(10,2) DEFAULT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_period` (`business_key`,`financial_year`,`gst_period`),
  KEY `idx_vendor` (`vendor_gstin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_return_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gst_return_id` int(11) NOT NULL,
  `section` varchar(50) NOT NULL,
  `reference_type` varchar(50) NOT NULL,
  `reference_id` int(11) NOT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `customer_gstin` varchar(15) DEFAULT NULL,
  `customer_name` varchar(200) DEFAULT NULL,
  `place_of_supply` int(11) DEFAULT NULL,
  `hsn_code` varchar(8) DEFAULT NULL,
  `taxable_value` decimal(10,2) DEFAULT 0.00,
  `gst_rate` decimal(5,2) DEFAULT 0.00,
  `cgst` decimal(10,2) DEFAULT 0.00,
  `sgst` decimal(10,2) DEFAULT 0.00,
  `igst` decimal(10,2) DEFAULT 0.00,
  `total_gst` decimal(10,2) DEFAULT 0.00,
  `total_value` decimal(10,2) DEFAULT 0.00,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_return` (`gst_return_id`),
  KEY `idx_section` (`section`),
  KEY `idx_reference` (`reference_type`,`reference_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_returns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `business_key` varchar(100) NOT NULL,
  `return_type` enum('gstr1','gstr3b','gstr2b','gstr9','gstr4','gstr6','gstr7','gstr8','cmp08') NOT NULL,
  `financial_year` varchar(9) NOT NULL,
  `gst_period` varchar(7) NOT NULL,
  `return_number` varchar(50) NOT NULL,
  `version` int(11) NOT NULL DEFAULT 1,
  `status` enum('draft','validated','ready_for_filing','filed','rejected','amended') DEFAULT 'draft',
  `generation_date` datetime DEFAULT NULL,
  `generated_by` varchar(100) DEFAULT NULL,
  `filed_date` datetime DEFAULT NULL,
  `filed_by` varchar(100) DEFAULT NULL,
  `filing_reference` varchar(100) DEFAULT NULL,
  `json_data` longtext DEFAULT NULL,
  `summary_data` longtext DEFAULT NULL,
  `validation_results` longtext DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_period` (`business_key`,`return_type`,`financial_year`,`gst_period`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `gst_settlements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `settlement_month` date NOT NULL,
  `total_input` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_output` decimal(10,2) NOT NULL DEFAULT 0.00,
  `net_payable` decimal(10,2) NOT NULL DEFAULT 0.00,
  `itc_opening` decimal(10,2) NOT NULL DEFAULT 0.00,
  `itc_closing` decimal(10,2) NOT NULL DEFAULT 0.00,
  `payment_status` enum('pending','paid','partial') NOT NULL DEFAULT 'pending',
  `payment_date` datetime DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_amount` decimal(10,2) DEFAULT 0.00,
  `remarks` text DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `settlement_month` (`settlement_month`),
  KEY `idx_status` (`payment_status`),
  KEY `idx_month` (`settlement_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_config` (
  `id` int(11) NOT NULL DEFAULT 1,
  `provider` varchar(50) NOT NULL DEFAULT 'openrouter',
  `api_key` text NOT NULL DEFAULT '',
  `model` varchar(100) NOT NULL DEFAULT 'openai/gpt-4o-mini',
  `max_tokens` int(11) NOT NULL DEFAULT 2048,
  `temperature` decimal(3,2) NOT NULL DEFAULT 0.70,
  `cache_ttl` int(11) NOT NULL DEFAULT 3600,
  `system_prompt` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `language_mode` varchar(20) NOT NULL DEFAULT 'hinglish',
  `azure_tts_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `azure_tts_key` text NOT NULL DEFAULT '',
  `azure_tts_region` varchar(100) NOT NULL DEFAULT '',
  `azure_tts_voice` varchar(100) NOT NULL DEFAULT 'hi-IN-SwaraNeural',
  `base_url` varchar(255) NOT NULL DEFAULT '',
  `openai_api_key` text NOT NULL DEFAULT '',
  `gemini_api_key` text NOT NULL DEFAULT '',
  `ollama_api_key` text NOT NULL DEFAULT '',
  `openrouter_api_key` text NOT NULL DEFAULT '',
  `groq_api_key` text NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_conversations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` varchar(128) NOT NULL,
  `user_id` int(11) NOT NULL,
  `role` varchar(50) NOT NULL,
  `message` text NOT NULL,
  `intent` varchar(100) DEFAULT NULL,
  `confidence` decimal(3,2) DEFAULT NULL,
  `response_time_ms` int(11) DEFAULT NULL,
  `tokens_used` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_session` (`session_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_feedback` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `rating` tinyint(4) DEFAULT NULL,
  `feedback_text` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_conversation` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_role_memory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role` varchar(50) NOT NULL,
  `memory_key` varchar(100) NOT NULL,
  `memory_value` text NOT NULL,
  `priority` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_key` (`role`,`memory_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_session_context` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` varchar(128) NOT NULL,
  `user_id` int(11) NOT NULL,
  `context_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`context_data`)),
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session` (`session_id`),
  KEY `idx_session` (`session_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ai_user_memory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `memory_key` varchar(100) NOT NULL,
  `memory_value` text NOT NULL,
  `confidence` decimal(3,2) NOT NULL DEFAULT 0.30,
  `context_tags` varchar(255) DEFAULT NULL,
  `last_accessed` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_key` (`user_id`,`memory_key`),
  KEY `idx_user` (`user_id`),
  KEY `idx_key` (`memory_key`),
  KEY `idx_confidence` (`confidence`),
  KEY `idx_accessed` (`last_accessed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;
